Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main("supplyAnalysis")
  File "main.py", line 60, in main
    inst.supp_call("theta2_NM")
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 107, in supp_call
    sol = root(self.supp_obj, X_p, method="lm")
  File "/usr/lib/python3/dist-packages/scipy/optimize/_root.py", line 187, in root
    sol = _root_hybr(fun, x0, args=args, jac=jac, **options)
  File "/usr/lib/python3/dist-packages/scipy/optimize/minpack.py", line 214, in _root_hybr
    shape, dtype = _check_func('fsolve', 'func', func, x0, args, n, (n,))
  File "/usr/lib/python3/dist-packages/scipy/optimize/minpack.py", line 27, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 85, in supp_obj
    self.X1[:, 0] = np.copy(self.X_p[:, 0])
IndexError: too many indices for array
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main("supplyAnalysis")
  File "main.py", line 60, in main
    inst.supp_call("theta2_NM")
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 107, in supp_call
    sol = root(self.supp_obj, X_p, method="lm")
  File "/usr/lib/python3/dist-packages/scipy/optimize/_root.py", line 189, in root
    sol = _root_leastsq(fun, x0, args=args, jac=jac, **options)
  File "/usr/lib/python3/dist-packages/scipy/optimize/_root.py", line 252, in _root_leastsq
    factor=factor, diag=diag)
  File "/usr/lib/python3/dist-packages/scipy/optimize/minpack.py", line 383, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/usr/lib/python3/dist-packages/scipy/optimize/minpack.py", line 27, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 85, in supp_obj
    self.X1[:, 0] = np.copy(self.X_p[:, 0])
IndexError: too many indices for array
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
File results/X_p_df-sane saved
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main("supplyAnalysis")
  File "main.py", line 60, in main
    inst.supp_call("theta2_NM")
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 108, in supp_call
    sol = root(self.supp_obj, X_p, method="krylov")
  File "/usr/lib/python3/dist-packages/scipy/optimize/_root.py", line 199, in root
    **options)
  File "/usr/lib/python3/dist-packages/scipy/optimize/_root.py", line 302, in _root_nonlin_solve
    raise_exception=False)
  File "/usr/lib/python3/dist-packages/scipy/optimize/nonlin.py", line 277, in nonlin_solve
    Fx = func(x)
  File "/usr/lib/python3/dist-packages/scipy/optimize/nonlin.py", line 273, in <lambda>
    func = lambda z: _as_inexact(F(_array_like(z, x0))).flatten()
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 85, in supp_obj
    self.X1[:, 0] = np.copy(self.X_p[:, 0])
ValueError: could not broadcast input array from shape (872,1) into shape (872)
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main("supplyAnalysis")
  File "main.py", line 60, in main
    inst.supp_call("theta2_NM")
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 108, in supp_call
    sol = root(self.supp_obj, X_p, method="df-sane")
  File "/usr/lib/python3/dist-packages/scipy/optimize/_root.py", line 193, in root
    **options)
  File "/usr/lib/python3/dist-packages/scipy/optimize/_spectral.py", line 89, in _root_df_sane
    f, x_k, x_shape, f_k, F_k, is_complex = _wrap_func(func, x0, fmerit, nfev, maxfev, args)
  File "/usr/lib/python3/dist-packages/scipy/optimize/_spectral.py", line 209, in _wrap_func
    F = np.asarray(func(x0, *args)).ravel()
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 85, in supp_obj
    self.X1[:, 0] = np.copy(self.X_p[:, 0])
ValueError: could not broadcast input array from shape (872,1) into shape (872)
File results_2e2/X_p_df-sane.pkl not found or load failed
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main("supplyAnalysis")
  File "main.py", line 60, in main
    inst.supp_call("theta2_NM")
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 106, in supp_call
    X_p = obj_load(self.params_dir, "X_p_krylov")
  File "/home/rbrandao/congelados/python_blp/BLP.py", line 18, in obj_load
    return x
UnboundLocalError: local variable 'x' referenced before assignment
File results_2e2/X_p_krylov.pkl not found or load failed
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main("supplyAnalysis")
  File "main.py", line 60, in main
    inst.supp_call("theta2_NM")
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 106, in supp_call
    X_p = obj_load(self.params_dir, "X_p_krylov")
  File "/home/rbrandao/congelados/python_blp/BLP.py", line 18, in obj_load
    return x
UnboundLocalError: local variable 'x' referenced before assignment
File results_2e2/X_p_krylov.pkl not found or load failed
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main("supplyAnalysis")
  File "main.py", line 60, in main
    inst.supp_call("theta2_NM")
  File "/home/rbrandao/congelados/python_blp/SupplyAnalysis.py", line 106, in supp_call
    X_p = obj_load(self.params_dir, "X_p_krylov")
  File "/home/rbrandao/congelados/python_blp/BLP.py", line 18, in obj_load
    return x
UnboundLocalError: local variable 'x' referenced before assignment
